### ISSUE TITLE
[Feature Request] Add button to web version to make all items Ascended

### ISSUE THREAD

**Issue by bmfrosty** [abramhindle/ttwl-cli-saveedit#3]
As in the description.  I didn't show up the code for it in a cursory search.

**Comment by abramhindle** [comment]
I don't like this idea personally because I think it violates the spirit of the game. You can do it with the commandline version yourself.
So for the web version I refuse to add it for now because I'm not interested in producing something for cheating or gear manufacturing.
That said, it is javascript and you can evaluate your own javascript.
Upload or load a savefile and then open the inspector (ctrl-shift-i) and go to the console and type this in and you should get ascended gear:
`
pkg.item_types(4); downloadInputFile("asc.sav"); 
`

**Comment by abramhindle** [comment]
Hi, bmfrosty try the new webui! It has lots of options now, especially for this request.

**Comment by bmfrosty** [comment]
It looks great.  I'm prepping for a weekend trip, but I should be able to
play with it when I get back.
